# Generated by Django 5.1.1 on 2024-11-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='professor',
        ),
    ]
