# Generated by Django 5.1.1 on 2024-11-09 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='category',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='category',
            name='min_score',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='score',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Categoria Padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='criterion',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='usuarios.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.criterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='usuarios.evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.user')),
            ],
        ),
    ]
