# Generated by Django 5.1.1 on 2024-11-29 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_equipe_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaofact',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='avaliacaofact',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='avaliacaofact',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='avaliacaofact',
            name='turma',
        ),
        migrations.AddField(
            model_name='avaliacaofact',
            name='avaliado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fact_avaliacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaofact',
            name='avaliador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fact_avaliacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaofact',
            name='criterio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.criterion'),
        ),
        migrations.AddField(
            model_name='avaliacaofact',
            name='justificativa',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaofact',
            name='nota',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
