# Generated by Django 5.1.1 on 2024-12-05 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_equipe_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterios_e_notas', models.JSONField()),
                ('justificativa', models.JSONField()),
                ('media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
