# Generated by Django 5.1.1 on 2024-12-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_justificativa_relatorioavaliacao_justificativas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioavaliacao',
            name='media',
        ),
        migrations.DeleteModel(
            name='RespostaFACT',
        ),
    ]
