# Generated by Django 5.1.3 on 2024-11-23 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_evaluation_name_alter_evaluation_evaluated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='criterion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='usuarios.criterion'),
        ),
        migrations.AddField(
            model_name='category',
            name='max_score',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='category',
            name='min_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='criterion',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='score',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluated',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='usuarios.user'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='usuarios.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuarios.turma'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='StudentResponse',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluated',
            field=models.ManyToManyField(related_name='evaluations_received', to='usuarios.user'),
        ),
    ]
