# Generated by Django 5.1.1 on 2024-11-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_category_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.criterion'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_score',
            field=models.IntegerField(),
        ),
    ]
